### ISSUE TITLE
Javascript UI library for trame

### ISSUE THREAD

**Issue by johnkit** [Kitware/geo-trame#79]
trame feature request:

trame makes use of Vuetify and Vue.js for defining user interfaces in applications. However, a number of trame customers want to use other UI frameworks such as React or Angular. This task entails developing a JavaScript library for trame that can be used with multiple UI frameworks. It would provide trame API for the client side (network setup, calling trigger, state update/reaction, action execution) and provide helper classes to support Local and Remote rendering.

**Comment by jourdain** [comment]
Done in https://github.com/Kitware/trame-client/tree/master/js-lib and available https://www.npmjs.com/package/@kitware/trame
